### ISSUE TITLE
 FATAL EXCEPTION: IntentService

### ISSUE THREAD

**Issue by WangGuox1n** [SecUSo/privacy-friendly-notes#76]
Hi,
I'm using version 1.0.1, when testing the app, there is a exception:

**STACK_TRACE**= E/AndroidRuntime(28326): FATAL EXCEPTION: IntentService[Notification service]
E/AndroidRuntime(28326): Process: org.secuso.privacyfriendlynotes, PID: 28326
E/AndroidRuntime(28326): **android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0**
E/AndroidRuntime(28326): 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
E/AndroidRuntime(28326): 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
E/AndroidRuntime(28326): 	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
E/AndroidRuntime(28326): 	at org.secuso.privacyfriendlynotes.NotificationService.onHandleIntent(NotificationService.java:28)
E/AndroidRuntime(28326): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime(28326): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(28326): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(28326): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by WangGuox1n** [comment]
Second exception:

**STACK_TRACE**= E/AndroidRuntime( 5958): Process: org.secuso.privacyfriendlynotes, PID: 5958
E/AndroidRuntime( 5958): java.lang.IllegalArgumentException: fromDate: Fri Jun 14 04:26:52 EDT 2019 does not precede toDate: Fri Jun 14 04:26:52 EDT 2019
E/AndroidRuntime( 5958): 	at android.widget.CalendarView.getWeeksSinceMinDate(CalendarView.java:1272)
E/AndroidRuntime( 5958): 	at android.widget.CalendarView.access$1500(CalendarView.java:76)
E/AndroidRuntime( 5958): 	at android.widget.CalendarView$WeeksAdapter.init(CalendarView.java:1356)
E/AndroidRuntime( 5958): 	at android.widget.CalendarView$WeeksAdapter.access$500(CalendarView.java:1337)
E/AndroidRuntime( 5958): 	at android.widget.CalendarView.setMinDate(CalendarView.java:753)
E/AndroidRuntime( 5958): 	at android.widget.DatePicker.setMinDate(DatePicker.java:323)
E/AndroidRuntime( 5958): 	at org.secuso.privacyfriendlynotes.ChecklistNoteActivity.onMenuItemClick(ChecklistNoteActivity.java:523)
E/AndroidRuntime( 5958): 	at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:201)
E/AndroidRuntime( 5958): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
E/AndroidRuntime( 5958): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
E/AndroidRuntime( 5958): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
E/AndroidRuntime( 5958): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
E/AndroidRuntime( 5958): 	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
E/AndroidRuntime( 5958): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime( 5958): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime( 5958): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/AndroidRuntime( 5958): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/AndroidRuntime( 5958): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 5958): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5958): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5958): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 5958): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5958): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5958): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 5958): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 5958): 	at dalvik.system.NativeStart.main(Native Method)
