### ISSUE TITLE
crash when adding reminder

### ISSUE THREAD

**Issue by anlalalu** [SecUSo/privacy-friendly-notes#77]
###### Reproduction Steps

1. select a note
2. tap 'set reminder'
3. tap 'Done'
4. tap 'Done'

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: IntentService[Notification service]
                                                 Process: org.secuso.privacyfriendlynotes, PID: 4944
                                                 android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                     at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
                                                     at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                     at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
                                                     at org.secuso.privacyfriendlynotes.NotificationService.onHandleIntent(NotificationService.java:28)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

###### Screen Shot

screen shot before crash:
![image](https://user-images.githubusercontent.com/46981872/71319251-8d460900-24d6-11ea-8513-bd11af3a20f5.png)

###### Debug info
App Version = 1.0.1

Android Version = 4.4.4

**Comment by petermayer** [comment]
Thanks for reporting! We will check if we can reproduce the error on our devices.
