### ISSUE TITLE
crash when editing reminder

### ISSUE THREAD

**Issue by anlalalu** [SecUSo/privacy-friendly-notes#78]
###### Reproduction Steps
When a reminder has been set:

1. select the note
2. tap 'set reminder'
3. tap 'Edit reminder'

###### Stack Trace
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.secuso.privacyfriendlynotes, PID: 5041
                                                 java.lang.IllegalArgumentException: fromDate: Sun Dec 22 03:11:27 EST 2019 does not precede toDate: Sun Dec 22 03:11:27 EST 2019
                                                     at android.widget.CalendarView.getWeeksSinceMinDate(CalendarView.java:1272)
                                                     at android.widget.CalendarView.access$1500(CalendarView.java:76)
                                                     at android.widget.CalendarView$WeeksAdapter.init(CalendarView.java:1356)
                                                     at android.widget.CalendarView$WeeksAdapter.access$500(CalendarView.java:1337)
                                                     at android.widget.CalendarView.setMinDate(CalendarView.java:753)
                                                     at android.widget.DatePicker.setMinDate(DatePicker.java:323)
                                                     at org.secuso.privacyfriendlynotes.SketchActivity.onMenuItemClick(SketchActivity.java:503)
                                                     at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:201)
                                                     at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
                                                     at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
                                                     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
                                                     at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:299)
                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
                                                     at android.widget.AbsListView$3.run(AbsListView.java:3645)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Screen Shot

screen shot before crash:

![image](https://user-images.githubusercontent.com/46981872/71319267-c1212e80-24d6-11ea-9113-2bec917ac4a7.png)

###### Debug info
App Version = 1.0.1

Android Version = 4.4.4

**Comment by petermayer** [comment]
Thanks for reporting! We will check whether we can reproduce the error on our devices.
