### ISSUE TITLE
crash when setting reminder to a previous time

### ISSUE THREAD

**Issue by anlalalu** [SecUSo/privacy-friendly-notes#79]
###### Reproduction Steps

1. create a note
2. set reminder, the time is current time
3. edit the reminder
4. set the time to a previous time
5. wait for a few seconds after the editing

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: IntentService[Notification service]
                                                 Process: org.secuso.privacyfriendlynotes, PID: 3464
                                                 android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                     at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
                                                     at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                     at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
                                                     at org.secuso.privacyfriendlynotes.NotificationService.onHandleIntent(NotificationService.java:28)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

###### Screen Shot
Set the reminder (reminding time is current time)
<img width="414" alt="add" src="https://user-images.githubusercontent.com/46981872/72158496-5425f800-33f5-11ea-9a21-814977919082.png">

<img width="441" alt="1" src="https://user-images.githubusercontent.com/46981872/72158271-c813d080-33f4-11ea-9444-c8b1ffd45c2f.png">
<img width="402" alt="2" src="https://user-images.githubusercontent.com/46981872/72158275-c9dd9400-33f4-11ea-84e5-00a2a61d3271.png">

Edit the reminder (adjust the reminding time to a previous time)
<img width="406" alt="edit" src="https://user-images.githubusercontent.com/46981872/72158502-57b97f00-33f5-11ea-8aca-8e2eff6f4006.png">

<img width="417" alt="3" src="https://user-images.githubusercontent.com/46981872/72158308-dd88fa80-33f4-11ea-8b33-38a8f0d3ccec.png">

Wait a few seconds
<img width="414" alt="4" src="https://user-images.githubusercontent.com/46981872/72158325-ebd71680-33f4-11ea-955a-b6aacc6cccab.png">

###### Debug info
App Version = the latest master branch

Android Version = 7.0.1

**Comment by anlalalu** [comment]
Can you reproduce this issue and do you judge it as a defect? If so, please let me know. Thank you!
